// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoxTzwXWZlmK0Ht1UJwFwP8L6OlfYJZ5c',
    appId: '1:681585932581:web:0849f3e2a29f39fe85c2cc',
    messagingSenderId: '681585932581',
    projectId: 'app7-572b3',
    authDomain: 'app7-572b3.firebaseapp.com',
    storageBucket: 'app7-572b3.appspot.com',
    measurementId: 'G-VCBE3DP1F7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeWHKBYjS62S2L4_8rP37Elq8E5j_xpzg',
    appId: '1:681585932581:android:3d8b7d9e13b0b30a85c2cc',
    messagingSenderId: '681585932581',
    projectId: 'app7-572b3',
    storageBucket: 'app7-572b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9KZDcipD2cXq13UdZ5cRI0HhV98M1jck',
    appId: '1:681585932581:ios:222d263aac65fc2785c2cc',
    messagingSenderId: '681585932581',
    projectId: 'app7-572b3',
    storageBucket: 'app7-572b3.appspot.com',
    iosClientId: '681585932581-j5ddhco89t4bq948rei83impkhv3ktt9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcommerce',
  );
}
